version: "3.8"

services:
  
  php:
    build:
      context: docker/php
    container_name: zenn-php-symfony
    restart: unless-stopped
    volumes:
      - ./backend/src:/var/www/zenn_example
    healthcheck:
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 30s

  nginx:
    build:
      context: docker/nginx
    container_name: zenn-nginx-symfony
    ports:
      - "8080:80"
    volumes:
      - ./backend/src:/var/www/zenn_example
    depends_on:
      - php

  mysql_master:
    container_name: mysql_master
    build:
      context: ./docker/mysql
      dockerfile: master.Dockerfile
    volumes:
      - ./volumes/mysql/master:/var/lib/mysql/
    tty: true
    ports:
      - "3306:3306"
    privileged: true
    platform: linux/amd64
    environment:
      TZ: 'Asia/Tokyo'
    logging:
      driver: json-file
      options:
        max-file: '1'
        max-size: 3m

  mysql_slave:
    container_name: mysql_slave
    build:
      context: ./docker/mysql
      dockerfile: slave.Dockerfile
    volumes:
      - ./volumes/mysql/slave:/var/lib/mysql/
    tty: true
    ports:
      - "3307:3306"
    platform: linux/amd64
    depends_on:
      - mysql_master
    environment:
      TZ: 'Asia/Tokyo'
    logging:
      driver: json-file
      options:
        max-file: '1'
        max-size: 3m
